In [1]:
import pandas as pd
import seaborn as sn
import numpy as np

df = pd.read_csv('spotify-tracks-dataset.csv')
print("Data loaded successfully...")
print("Shape: ",df.shape)

Data loaded successfully...
Shape:  (114000, 22)

In [2]:
df.head(10)

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
5,5,5,01MVOl9KtVTNfFiBU9I7dc,Tyrone Wells,Days I Will Remember,Days I Will Remember,58,214240,False,0.688,...,-8.807,1,0.1050,0.2890,0.000000,0.1890,0.6660,98.017,4,acoustic
6,6,6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,...,-8.822,1,0.0355,0.8570,0.000003,0.0913,0.0765,141.284,3,acoustic
7,7,7,1EzrEOXmMH3G43AXT1y7pA,Jason Mraz,We Sing. We Dance. We Steal Things.,I'm Yours,80,242946,False,0.703,...,-9.331,1,0.0417,0.5590,0.000000,0.0973,0.7120,150.960,4,acoustic
8,8,8,0IktbUcnAGrvD03AWnz3Q8,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,74,189613,False,0.625,...,-8.700,1,0.0369,0.2940,0.000000,0.1510,0.6690,130.088,4,acoustic
9,9,9,7k9GuJYLp2AzqokyEdwEw2,Ross Copperman,Hunger,Hunger,56,205594,False,0.442,...,-6.770,1,0.0295,0.4260,0.004190,0.0735,0.1960,78.899,4,acoustic

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0.1      114000 non-null  int64
 1   Unnamed: 0        114000 non-null  int64
 2   track_id          114000 non-null  object
 3   artists           113999 non-null  object
 4   album_name        113999 non-null  object
 5   track_name        113999 non-null  object
 6   popularity        114000 non-null  int64
 7   duration_ms       114000 non-null  int64
 8   explicit          114000 non-null  bool
 9   danceability      114000 non-null  float64
 10  energy            114000 non-null  float64
 11  key               114000 non-null  int64
 12  loudness          114000 non-null  float64
 13  mode              114000 non-null  int64
 14  speechiness       114000 non-null  float64
 15  acousticness      114000 non-null  float64
 16  instrumentalness  114000 non-null  float64
 17  liveness          114000 non-null  float64
 18  valence           114000 non-null  float64
 19  tempo             114000 non-null  float64
 20  time_signature    114000 non-null  int64
 21  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(7), object(5)
memory usage: 18.4+ MB

In [4]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

In [5]:
df = df.drop(columns = ['Unnamed: 0.1', 'Unnamed: 0'])
print("Cleaned. New shape: ",df.shape)

Cleaned. New shape:  (114000, 20)

In [6]:
df = df.dropna()
print("After dropping nulls", df.shape)

After dropping nulls (113999, 20)

In [7]:
df['duration_sec'] = df['duration_ms']/1000
print("Duration column added")

Duration column added

In [12]:
print("Most Common Genres:")
print(df['track_genre'].value_counts().head(10))

print("\nAverage Populatiry",df['popularity'].mean().round(2))
print("Most Popular Track:")
print(df.loc[df['popularity'].idxmax(), ['track_name', 'artists', 'popularity']])

Most Common Genres:
track_genre
acoustic             1000
afrobeat             1000
psych-rock           1000
progressive-house    1000
power-pop            1000
pop                  1000
pop-film             1000
piano                1000
party                1000
pagode               1000
Name: count, dtype: int64

Average Populatiry 33.24
Most Popular Track:
track_name    Unholy (feat. Kim Petras)
artists            Sam Smith;Kim Petras
popularity                          100
Name: 20001, dtype: object

In [14]:
genre_energy = df.groupby('track_genre')['energy'].mean()
genre_energy = genre_energy.sort_values(ascending = False)
print("Top 10 highest energy genres:", genre_energy.head(10))
print("Top 10 lowest energy genres:", genre_energy.tail(10))

Top 10 highest energy genres: track_genre
death-metal      0.931470
grindcore        0.924201
metalcore        0.914485
happy            0.910971
hardstyle        0.901246
drum-and-bass    0.876635
black-metal      0.874897
heavy-metal      0.874003
party            0.871237
j-idol           0.868677
Name: energy, dtype: float64
Top 10 lowest energy genres: track_genre
jazz         0.352954
sleep        0.342072
guitar       0.324999
piano        0.320103
opera        0.317054
disney       0.302519
romance      0.294304
ambient      0.237162
new-age      0.214501
classical    0.189827
Name: energy, dtype: float64

In [17]:
genre_dance = df.groupby('track_genre')['danceability'].mean()
genre_dance = genre_dance.sort_values(ascending = False)
print("Top 10 Danceable Tracks:",genre_dance.head(10))
print("\nBottom 10 Danceable Tracks:",genre_dance.tail(10))

Top 10 Danceable Tracks: track_genre
kids              0.778906
chicago-house     0.766176
reggaeton         0.758521
latino            0.757057
reggae            0.745331
hip-hop           0.736154
dancehall         0.734169
minimal-techno    0.729395
detroit-techno    0.722568
latin             0.721902
Name: danceability, dtype: float64

Bottom 10 Danceable Tracks: track_genre
world-music    0.414572
classical      0.381923
death-metal    0.368411
ambient        0.367867
new-age        0.348455
opera          0.313563
iranian        0.300686
black-metal    0.296411
grindcore      0.271854
sleep          0.167923
Name: danceability, dtype: float64

In [19]:
features = ['danceability', 'energy', 'loudness', 'speechiness', 
            'acousticness', 'instrumentalness', 'liveness', 
            'valence', 'tempo', 'duration_sec']
correlations = df[features].corrwith(df['popularity'])
correlations = correlations.sort_values(ascending = False)
print(correlations.round(3))

loudness            0.050
danceability        0.035
tempo               0.013
energy              0.001
liveness           -0.005
duration_sec       -0.007
acousticness       -0.025
valence            -0.041
speechiness        -0.045
instrumentalness   -0.095
dtype: float64

Surprisingly, no audio feature strongly predicts song popularity. The highest correlation is loudness at only 0.05, suggesting that popularity is driven by factors outside of audio characteristics such as artist fame, marketing, and cultural relevance. The strongest finding is that instrumental tracks tend to be less popular than vocal tracks.